version: '3'

services:
  web:
    image: php:8.0.0-apache
    volumes:
      - ./src/:/var/www/html/
    ports:
      - 8000:80
  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    volumes:
      - ./seed/:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
    depends_on:
      - db  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/nginx.d/proxy.conf
      - ./certs/www.supersite.com.crt:/etc/pki/tls/private/
      - ./certs/www.supersite.com.key:/etc/pki/tls/certs/
    depends_on:
      - web
      - phpmyadmin
